import os
import datetime
from flask import Flask, request, jsonify
from flask_cors import CORS
from dotenv import load_dotenv
import bcrypt
import google.generativeai as genai
from db_middleware import db_middleware  # Import our new middleware

# Load environment variables
load_dotenv()

app = Flask(__name__)
CORS(app)  # Allow React frontend to communicate with this backend

# Configure Gemini AI
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if GEMINI_API_KEY:
    genai.configure(api_key=GEMINI_API_KEY)

# --- BPO TOOLS & CONNECTIVITY ---
def lookup_crm(identifier: str):
    """
    Simulates a connection to Salesforce or a Business Database.
    Looks up customer details by email or phone number.
    """
    print(f"--- CRM TOOL CALLED for: {identifier} ---")
    
    try:
        # REAL DB LOOKUP: Query the 'users' table (or 'customers' if you have one)
        query = "SELECT name, email, role, subscription_tier, usage_balance FROM users WHERE email = :email"
        result = db_middleware.execute_query(query, {"email": identifier}).mappings().fetchone()
        
        if result:
            # Convert to dict and return to Gemini
            return dict(result)
        else:
            return {"error": "Customer not found in database."}
    except Exception as e:
        print(f"CRM Lookup Error: {e}")
        return {"error": "Database connection failed during lookup."}

def get_auth_token():
    auth_header = request.headers.get('Authorization')
    if auth_header and auth_header.startswith('Bearer '):
        return auth_header.split(" ")[1]
    return None

@app.route('/api/health', methods=['GET'])
def health_check():
    return jsonify({"status": "ok", "message": "Python Backend with Throttled Middleware is running"}), 200

@app.route('/api/login', methods=['POST'])
def login():
    data = request.json
    if not data or 'email' not in data or 'password' not in data:
        return jsonify({"error": "Missing email or password"}), 400

    email = data['email']
    password = data['password']

    try:
        # Use middleware for pooled connection
        query = "SELECT id, email, role, name, status, subscription_tier, usage_balance, password FROM users WHERE email = :email"
        result = db_middleware.execute_query(query, {"email": email}).mappings().fetchone()

        if result:
            user = dict(result)
            stored_password = user.get('password')
            
            # 1. Try verifying as a bcrypt hash
            if stored_password:
                try:
                    if bcrypt.checkpw(password.encode('utf-8'), stored_password.encode('utf-8')):
                        user.pop('password', None) # Safely remove password
                        return jsonify({"message": "Login successful", "user": user}), 200
                except (ValueError, TypeError):
                    # 2. Fallback: Plain text check
                    if stored_password == password:
                        user.pop('password', None)
                        return jsonify({"message": "Login successful", "user": user}), 200
            
            return jsonify({"error": "Invalid credentials"}), 401
        else:
            return jsonify({"error": "User not found"}), 404
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/process-result', methods=['POST'])
def process_result():
    """Example of a high-concurrency route using batch writing with usage guards."""
    token = get_auth_token()
    if not token:
        return jsonify({"error": "Unauthorized"}), 401

    # Stateless verification (No DB hit for signature check)
    user_payload = db_middleware.verify_token(token)
    if "error" in user_payload:
        return jsonify(user_payload), 401

    user_id = user_payload['id']

    # --- MONETIZATION GUARD ---
    # Attempt to decrement usage balance atomically
    permitted, new_balance = db_middleware.check_and_decrement_usage(user_id)
    
    if not permitted:
        return jsonify({
            "error": "Usage Limit Exceeded", 
            "message": "Your current protocol balance is 0. Please upgrade your tier.",
            "code": "LIMIT_REACHED"
        }), 402

    data = request.json
    # Buffer the result for batch writing
    db_middleware.buffer_write("process_logs", {
        "user_id": user_id,
        "result_data": str(data.get('result')),
        "created_at": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    })

    return jsonify({
        "status": "success", 
        "message": "Reasoning unit consumed successfully",
        "remaining_balance": new_balance
    }), 200

@app.route('/api/vapi/bpo-chat', methods=['POST'])
def vapi_bpo_chat():
    """
    Endpoint for Vapi.ai to fetch responses generated by Gemini.
    Acts as the 'Custom LLM' for the Vapi Assistant.
    """
    if not GEMINI_API_KEY:
        return jsonify({"error": "Gemini API Key not configured"}), 500

    data = request.json
    # Vapi sends a list of messages. We extract them to build context.
    messages = data.get('messages', [])
    
    # Extract Metadata for Business Use Case Testing
    # Vapi allows passing 'metadata' in the call object. We use this to switch scenarios.
    call_data = data.get('call', {})
    metadata = call_data.get('metadata', {})
    scenario = metadata.get('scenario', 'support') # Default to support
    
    # Define BPO Persona
    base_instruction = "You are a professional Voice AI BPO agent. Keep responses concise, conversational, and suitable for voice synthesis. Do not use markdown."
    
    if scenario == 'sales':
        system_instruction = f"{base_instruction} You are an aggressive but polite Sales Representative. Your goal is to upsell the 'Platinum Tier'. Use the 'lookup_crm' tool to check lead status."
    else:
        # Default Support Persona
        system_instruction = f"{base_instruction} You are a helpful Customer Support Agent. Always verify the user's identity using the 'lookup_crm' tool if they ask for account details."

    try:
        # Use Gemini 1.5 Flash for low latency (crucial for Voice AI)
        # Configure tools for connectivity
        tools = [lookup_crm]
        model = genai.GenerativeModel('gemini-1.5-flash', tools=tools, system_instruction=system_instruction)
        
        # Construct a prompt from the conversation history
        # We convert Vapi messages to Gemini ChatHistory format
        chat_history = []
        for msg in messages:
            role = msg.get('role', 'user')
            # Map Vapi roles to Gemini roles
            if role == 'assistant': role = 'model'
            content = msg.get('content', '')
            chat_history.append({"role": role, "parts": [content]})
        
        # Start chat with history
        chat = model.start_chat(history=chat_history[:-1] if chat_history else [])
        last_message = chat_history[-1]['parts'][0] if chat_history else "Hello"

        # Generate response with automatic function calling enabled
        response = chat.send_message(last_message, request_options={"timeout": 10})
        response_text = response.text.strip()

        # Return in OpenAI-compatible format (Standard for Vapi Custom LLMs)
        return jsonify({
            "choices": [{
                "index": 0,
                "message": {"role": "assistant", "content": response_text},
                "finish_reason": "stop"
            }]
        })

    except Exception as e:
        print(f"Gemini BPO Error: {e}")
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    print(f"Starting High-Concurrency Python Backend on port 5000...")
    app.run(debug=True, host='0.0.0.0', port=5000)
